_target_: diffusion_policy.workspace.train_mbc_lowdim_workspace.TrainMBCLowdimWorkspace
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 2
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 8
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: train_mbc_pusht_lowdim
  project: diffusion_policy_debug
  resume: true
  tags:
  - train_mbc_pusht_lowdim
  - pusht_lowdim
  - default
multi_run:
  run_dir: /common/users/hc856/Project/diffusion_policy/data/outputs/train_mbc_pusht_lowdim
  wandb_name_base: train_mbc_pusht_lowdim
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 2
name: train_mbc_pusht_lowdim
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.mbc_lowdim_policy.MBCLowdimPolicy
  horizon: 8
  obs_dim: 5
  action_dim: 2
  n_action_steps: 8
  n_obs_steps: 2
  n_max_modality: 2
  down_dims: [256, 512, 1024]
  kernel_size: 3
  n_groups: 8
shape_meta:
  action:
    shape:
    - 2
  obs:
    agent_pos:
      shape:
      - 2
      type: low_dim
    image:
      shape:
      - 3
      - 96
      - 96
      type: rgb
task:
  dataset:
    _target_: diffusion_policy.dataset.pusht_state_dataset.PushTStateDataset
    horizon: 8
    max_train_episodes: 10000  # set to a very large number
    pad_after: 7
    pad_before: 1
    seed: 42
    val_ratio: 0.1
    zarr_path: data/kowndi_pusht_demo_v2_repulse.zarr
  env_runner:
    _target_: diffusion_policy.env_runner.pusht_state_runner.PushTStateRunner
    fps: 10
    legacy_test: true
    max_steps: 300
    n_action_steps: 8
    n_envs: null
    n_obs_steps: 2
    n_test: 50
    n_test_vis: 4
    n_train: 6
    n_train_vis: 2
    past_action: false
    test_start_seed: 100000
    train_start_seed: 0
  image_shape:
  - 3
  - 96
  - 96
  name: pusht_lowdim
  shape_meta:
    action:
      shape:
      - 2
    obs:
      agent_pos:
        shape:
        - 2
        type: low_dim
      image:
        shape:
        - 3
        - 96
        - 96
        type: rgb
      control:
        shape:
        - 3
        - 96
        - 96
task_name: pusht_lowdim
training:
  checkpoint_every: 50
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 3050
  resume: true
  rollout_every: 50
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1
val_dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false
